from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from prop import *
import time
driver = webdriver.Chrome()
# driver=webdriver.firefox()
def login():
    driver.get(website.url)
    driver.maximize_window()
    driver.find_element_by_xpath(loginlocator.userfield).send_keys(Configlogin.username)
    driver.find_element_by_xpath(loginlocator.passwordfield).send_keys(Configlogin.pwd)
    driver.find_element_by_xpath(loginlocator.loginbutton).click()
def logout():
    driver.find_element_by_xpath(loginlocator.welcomebutton).click()
    time.sleep(2)
    driver.find_element_by_xpath(loginlocator.logoutbutton).click()
def admin_user_management():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    time.sleep(5)
    driver.find_element_by_xpath(AdminTabslocater.Usermanagementbutton).click()
    time.sleep(5)
    driver.find_element_by_xpath(AdminTabslocater.UserButton).click()
    time.sleep(5)
    driver.find_element_by_xpath(AdminTabslocater.UserAddButton).click()
    time.sleep(5)
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    time.sleep(5)
def admin_job ():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    driver.find_element_by_xpath(AdminTabslocater.JobButton).click()
    driver.find_element_by_xpath(AdminTabslocater.JobTitleButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.JobButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.PayGrades).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.JobButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.EmploymentStatus).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.JobButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.JobCategory).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.JobButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.WorkShift).click()
    time.sleep(2)
def admin_Organization ():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    driver.find_element_by_xpath(AdminTabslocater.Organization).click()
    driver.find_element_by_xpath(AdminTabslocater.GeneralInformation).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Organization).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.ViewLocations).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Organization).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.CompanyStructure).click()
def admin_Qualifications ():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    driver.find_element_by_xpath(AdminTabslocater.Qualifications).click()
    driver.find_element_by_xpath(AdminTabslocater.ViewSkills).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Qualifications).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.ViewEducation).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Qualifications).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Licenses).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Qualifications).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Languages).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Qualifications).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Membership).click()
def admin_Nationality ():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    driver.find_element_by_xpath(AdminTabslocater.Nationality).click()
def admin_Configuration ():
    driver.find_element_by_xpath(AdminTabslocater.Adminbutton).click()
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    driver.find_element_by_xpath(AdminTabslocater.MailConfiguration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.EmailSubscriptions).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Localization).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.ViewModules).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.SocialMediaAuthentication).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(AdminTabslocater.RegisterOAuthClient).click()
def Directory ():
    driver.find_element_by_xpath(AdminTabslocater.Directory).click()
def Recruitment ():
    driver.find_element_by_xpath(RecruitmentTabslocater.Recruitment).click()
    driver.find_element_by_xpath(RecruitmentTabslocater.Candidates).click()
    time.sleep(2)
    driver.find_element_by_xpath(RecruitmentTabslocater.Recruitment).click()
    driver.find_element_by_xpath(RecruitmentTabslocater.Vacancy).click()
def admin_Leave ():
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    driver.find_element_by_xpath(LeaveTabslocater.ApplyLeave).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.MyLeave).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Entitlements).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.AddEntitlement).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Entitlements).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.EmployeeEntitlements).click()
    driver.find_element_by_xpath(LeaveTabslocater.Entitlements).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.MyEntitlements).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveList).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.AssignLeave).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Reports).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.ViewLeaveBalanceReport).click()
    driver.find_element_by_xpath(LeaveTabslocater.Reports).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.MyLeaveEntitlementsandUsageReport).click()
    driver.find_element_by_xpath(LeaveTabslocater.LeaveButton).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Configure).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeavePeriod).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Configure).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.LeaveType).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Configure).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.WorkingWeek).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.Configure).click()
    time.sleep(2)
    driver.find_element_by_xpath(LeaveTabslocater.HolidayList).click()
def admin_time():
    driver.find_element_by_xpath(TimeTabslocater.TimeButton).click()
    driver.find_element_by_xpath(TimeTabslocater.Timesheets).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.MyTimesheet).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Timesheets).click()
    driver.find_element_by_xpath(TimeTabslocater.EmployeeTimesheet).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Attendance).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.MyAttendance).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Attendance).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.PunchIn).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Attendance).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.ViewAttendanceRecord).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Attendance).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.AttendanceConfigure).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.TimeButton).click()
    driver.find_element_by_xpath(TimeTabslocater.Reports).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.ProjectReport).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Reports).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.EmployeeReport).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Reports).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.SummaryReport).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.TimeButton).click()
    driver.find_element_by_xpath(TimeTabslocater.ProjectInfo).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Customers).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.ProjectInfo).click()
    time.sleep(2)
    driver.find_element_by_xpath(TimeTabslocater.Projects).click()

def admin_Performance():

    driver.find_element_by_xpath(PerformanceTabLocater.Configure).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.Tracker).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.Performance).click()
    driver.find_element_by_xpath(PerformanceTabLocater.ManageReviews).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.Review).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.ManageReviews).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.MyReviews).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.ManageReviews).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.ReviewList).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.Performance).click()
    driver.find_element_by_xpath(PerformanceTabLocater.MyTracker).click()
    time.sleep(2)
    driver.find_element_by_xpath(PerformanceTabLocater.Performance).click()
    driver.find_element_by_xpath(PerformanceTabLocater.EmployeeTracker).click()

def admin_PIM():
    driver.find_element_by_xpath(PIMButtoneTabLocater.PIMButton).click()
    driver.find_element_by_xpath(PIMButtoneTabLocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.ConfigurePim).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.CustomFields).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.CsvImport).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.ReportingMethods).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.Configuration).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.TerminationReasons).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.PIMButton).click()
    driver.find_element_by_xpath(PIMButtoneTabLocater.EmployeeList).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.PIMButton).click()
    driver.find_element_by_xpath(PIMButtoneTabLocater.AddEmployee).click()
    time.sleep(2)
    driver.find_element_by_xpath(PIMButtoneTabLocater.PIMButton).click()
    driver.find_element_by_xpath(PIMButtoneTabLocater.Reports).click()


print("ALL Test Cases Pass and Ready for Production" )




